services:
  - type: web
    name: snaplabs-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USE_CHAINLIT
        value: false
      - key: OPENAI_API_KEY
        sync: false # This will be set manually in Render dashboard
    autoDeploy: true
